INSERT INTO riviste (nome, editore) VALUES
    ('Moto Magazine', 'Motors Publishing'),
    ('AI Today', 'Tech Media'),
    ('Extreme Bikers', 'Adventure Press'),
    ('Tech Trends', 'Innovation Corp'),
    ('Auto World', 'Wheels Media'),
    ('Focus', 'Science & Tech'),
    ('Speed & Sport', 'Sports Publications'),
    ('AI Insights', 'Tech Media'),
    ('Einaudi Tech', 'Einaudi'),
    ('Racing Enthusiast', 'FastTrack Publishing'),
    ('Drive Ahead', 'AutoTech Publishers'),
    ('Science Discoveries', 'Science & Tech'),
    ('Power Machines', 'Motor Enthusiasts'),
    ('Autonomous Future', 'AutoTech Publishers'),
    ('Tech in Medicine', 'HealthTech Press'),
    ('Tech Review', 'Tech Media'),
    ('Race Day', 'FastTrack Publishing'),
    ('Advanced AI Solutions', 'Tech Media'),
    ('Innovative Auto Trends', 'AutoTech Publishers'),
    ('Motorcycles Unlimited', 'Riders Media');

INSERT INTO articoli (riviste_id, titolo, argomento) VALUES
    (1, 'The Thrill of Moto Racing', 'motociclismo'),
    (1, 'A Look at MotoGP 2023', 'motociclismo'),
    (2, 'Introduction to Artificial Intelligence', 'Intelligenza Artificiale'),
    (2, 'Practical Applications of AI', 'Intelligenza Artificiale'),
    (3, 'Advanced Technologies for Bikers', 'motociclismo'),
    (4, 'The Future of AI - A Focus Feature', 'Intelligenza Artificiale'),
    (4, 'AI in Healthcare', 'Intelligenza Artificiale'),
    (5, 'Formula 1 2023 Season Preview', 'automobilismo'),
    (5, 'Trends in the World of Auto Racing', 'automobilismo'),
    (6, 'Extreme Motorcycle Adventures', 'motociclismo'),
    (7, 'AI and Digital Transformation', 'Intelligenza Artificiale'),
    (7, 'Autonomous Driving: A Glimpse into the Future', 'Intelligenza Artificiale'),
    (8, 'AI in Industry', 'Intelligenza Artificiale'),
    (9, 'Science Focus: Unraveling the Universe', 'scienza'),
    (9, 'The Secrets of the Cosmos', 'scienza'),
    (10, 'The Latest in Motorcycling', 'motociclismo'),
    (11, 'AI and the Internet of Things', 'Intelligenza Artificiale'),
    (12, 'Luxury Auto World', 'automobilismo'),
    (13, 'Revolutionizing Autonomous Driving', 'automobilismo'),
    (14, 'AI and Medicine: A Winning Combination', 'Intelligenza Artificiale'),
    (15, 'Tech Focus: The Future of Technology', 'tecnologia'),
    (15, 'Future Tech Trends', 'tecnologia'),
    (16, 'AI and Robotics', 'Intelligenza Artificiale'),
    (17, 'Eco-Friendly Auto Racing', 'automobilismo'),
    (18, 'AI in Finance', 'Intelligenza Artificiale'),
    (19, 'MotoGP 2023: Preview and Predictions', 'motociclismo'),
    (20, 'Recent Developments in AI', 'Intelligenza Artificiale');